<a href="https://colab.research.google.com/github/manhdino/deeplearning-googlecollab/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tensors đơn giản là mảng nhiều chiều >= 3 chiều
# 2 chiều --> vector
# 1 chiều --> array
# 0 chiều --> số 1,2,4...
# Tensors shape:
# 0 chiều --> ko có shape
# 1 chiều --> shape chính là số phần tử(số cột) (col,)
# 2 chiều --> shape (row,col)
# 3 chiều --> shape(row,row,col)

import tensorflow as tf

tensor_zero_d = tf.constant(4)
print(tensor_zero_d)
print(tensor_zero_d.shape)

tensor_one_d = tf.constant([1,2,3.5,5,4],dtype=tf.float16)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)
print(tensor_one_d.shape)

tensor_bool = tf.constant([True,False,False])
print(tensor_bool)
print(tensor_bool.shape)

tensor_string = tf.constant(['a','b','c'])
print(tensor_string)
print(tensor_string.shape)

tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)
print(tensor_two_d.shape)

tensor_three_d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_three_d)
print(tensor_three_d.shape)
print(tensor_three_d.ndim)

tensor_four_d = tf.constant([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(tensor_four_d)
print(tensor_four_d.shape)

# Numpy (Numeric Python): là một thư viện toán học phổ biến và mạnh mẽ của Python.
# Cho phép làm việc hiệu quả với ma trận và mảng,
# đặc biệt là dữ liệu ma trận và mảng lớn với tốc độ xử lý nhanh hơn nhiều lần khi chỉ sử dụng “core Python” đơn thuần

# Mảng trong numpy gồm các phần tử có dùng kiểu giá trị, chỉ số không âm được bắt đầu từ
# 0, số chiều được gọi là rank của mảng Numpy, và shape của mảng là một tuple các số nguyên đưa
# ra kích thước của mảng theo mỗi chiều

#Tuple

# Tạo một tuple
t = (1, 2, 3, 4, 5)

# Truy cập phần tử trong tuple bằng chỉ số
print(t[0])  # Output: 1
print(t[2])  # Output: 3

# Tuple có thể chứa các giá trị khác nhau
t2 = ('apple', 'banana', 1, 2.5)

# Truy cập phần tử cuối cùng
print(t2[-1])  # Output: 2.5

# Tạo một tuple để lưu thông tin về một người
person = ('John', 25, 'New York')

# Truy cập các phần tử của tuple
name = person[0]
age = person[1]
city = person[2]

print(f"Name: {name}, Age: {age}, City: {city}")
# Output: Name: John, Age: 25, City: New York

# Tạo một nested tuple
nested_tuple = ((1, 2), ('a', 'b', 'c'), (True, False))

# Truy cập phần tử bên trong nested tuple
print(nested_tuple[0])    # Output: (1, 2)
print(nested_tuple[1][2]) # Output: 'c'
print(nested_tuple[2][0]) # Output: True


# Không thể thay đổi giá trị của tuple sau khi đã tạo
t = (1, 2, 3)
# t[0] = 5  # Lỗi: TypeError: 'tuple' object does not support item assignment

# Tuy nhiên, có thể tạo một tuple mới bằng cách nối các tuple khác
t = t + (4, 5)
print(t)  # Output: (1, 2, 3, 4, 5)


# Sử dụng tuple làm key trong một dictionary
dict_example = {('Alice', 25): 'Engineer', ('Bob', 30): 'Doctor'}

# Truy cập giá trị bằng key tuple
print(dict_example[('Alice', 25)])  # Output: Engineer
print(dict_example[('Bob', 30)])    # Output: Doctor

#Tuple và mảng (array) sự khác nhau trong Python

# Tuple
# 1.Immutable (Bất biến):

# Tuple là một cấu trúc dữ liệu bất biến trong Python, có nghĩa là sau khi một tuple được tạo, các phần tử của nó không thể thay đổi. Bạn không thể thêm, xóa hoặc thay đổi các phần tử của một tuple sau khi nó đã được khởi tạo.

# 2.Các phần tử có thể có các kiểu dữ liệu khác nhau:

# Mỗi phần tử trong một tuple có thể có một kiểu dữ liệu khác nhau. Ví dụ: ('apple', 3, True) là một tuple hợp lệ trong Python.

# 3.Dùng để lưu trữ dữ liệu không thay đổi:

# Tuple thường được sử dụng để lưu trữ các bộ giá trị không thay đổi, ví dụ như thông tin về một đối tượng như tên, tuổi, địa chỉ.

# 4.Được sử dụng làm key trong dictionary:

# Do tính bất biến của nó, tuple có thể được sử dụng làm key trong một dictionary.

# 5.Dễ dàng khai báo và sử dụng:

# Khai báo tuple bằng cách đặt các giá trị trong cặp dấu ngoặc đơn và phân cách bởi dấu phẩy. Truy cập phần tử trong tuple cũng rất đơn giản bằng cách sử dụng chỉ số.

# Mảng (Array)
# 1.Mutable (Thay đổi được):

# Mảng trong Python, đặc biệt là mảng trong NumPy, là một cấu trúc dữ liệu có thể thay đổi. Bạn có thể thay đổi các phần tử của mảng, thêm hoặc xóa các phần tử một cách linh hoạt.

# 2.Các phần tử có cùng kiểu dữ liệu:

# Mỗi phần tử trong một mảng NumPy phải có cùng kiểu dữ liệu. Điều này giúp tối ưu hóa hiệu suất và các phép toán trên dữ liệu số học.

# 3.Dùng cho tính toán số học và xử lý dữ liệu lớn:

# Mảng trong NumPy được sử dụng phổ biến trong tính toán số học, xử lý dữ liệu lớn và các thuật toán máy học vì hiệu suất cao và tính năng xử lý dữ liệu mạnh mẽ của nó.

# 4.Shape (Hình dạng) và Rank (Số chiều):

# Mảng trong NumPy có khái niệm shape (hình dạng), là một tuple biểu diễn kích thước của mảng theo mỗi chiều, và rank (số chiều), là số lượng chiều của mảng. Ví dụ, một mảng 2 chiều có shape là (3, 4).

# 5.Cung cấp các hàm và phương thức xử lý mảng:

# Dictionary
# Dictionary (từ điển) là một cấu trúc dữ liệu mạnh mẽ và linh hoạt, cho phép lưu trữ và truy xuất các cặp key-value.
# Mỗi key phải là duy nhất và không thay đổi (immutable), trong khi đó, các value có thể là bất kỳ đối tượng Python nào, bao gồm cả số, chuỗi, danh sách, tuple, hoặc thậm chí là một dictionary khác.

# Tạo một dictionary để lưu thông tin của một người
person = {
    'name': 'John',
    'age': 30,
    'city': 'New York'
}

print(person)
# Output: {'name': 'John', 'age': 30, 'city': 'New York'}

# Truy cập giá trị của key 'name'
print(person['name'])  # Output: John

# Thay đổi giá trị của key 'age'
person['age'] = 32
print(person['age'])   # Output: 32


# Thêm một phần tử mới vào dictionary
person['job'] = 'Engineer'
print(person)
# Output: {'name': 'John', 'age': 32, 'city': 'New York', 'job': 'Engineer'}

# Xóa một phần tử khỏi dictionary
del person['city']
print(person)
# Output: {'name': 'John', 'age': 32, 'job': 'Engineer'}

# Lấy danh sách các key
keys = list(person.keys())
print(keys)  # Output: ['name', 'age', 'job']

# Lấy danh sách các value
values = list(person.values())
print(values)  # Output: ['John', 32, 'Engineer']

# Lấy danh sách các cặp (key, value)
items = list(person.items())
print(items)  # Output: [('name', 'John'), ('age', 32), ('job', 'Engineer')]





In [ ]:
import numpy as np

# Tạo mảng 1 chiều
np_array = np.array([1, 2, 3])
print(np_array)  # Output: [1 2 3]

converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)  # Output: Tensor([1, 2, 3], shape=(3,), dtype=int32)

# Identity Tensor (Tensor Đơn Vị)
# Trong đại số tensor, tensor đơn vị là một tensor có các thành phần đặc biệt sao cho khi nhân nó với một tensor khác, kết quả là chính tensor đó.
# Đối với tensor đơn vị, các phần tử trên đường chéo chính (đường từ góc trên bên trái đến góc dưới bên phải) đều bằng 1, các phần tử khác đều bằng 0.


# Tạo identity tensor 3x3
# eye_tensor = tf.eye(
#     num_rows = 3,
#     num_columns=3,
#     batch_shape=None,
#     dtype=tf.dtypes.float32,
#     name=None
# )


# print(eye_tensor)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# Tạo identity tensor 5x3:
# eye_tensor = tf.eye(
#     num_rows = 5,
#     num_columns=3,
#     batch_shape=None,
#     dtype=tf.dtypes.float32,
#     name=None
# )
# print(eye_tensor)
# Ouput
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]
#  [0. 0. 0.]]
# Lý do chỉ có 3 số 1 vì nó đã bị cắt mất 2 cột so với 5x5
# identity_tensor_square = np.eye(5)
# print(identity_tensor_square)
# Output
# [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 1.]]


# batch_shape: Hình dạng của batch tensor.
# Nếu bạn muốn tạo nhiều identity tensor như một batch, bạn có thể chỉ định batch_shape là một tuple các số nguyên, xác định kích thước của mỗi chiều batch tensor.
# eye_tensor = tf.eye(
#     num_rows = 5,
#     num_columns=3,
#     batch_shape=(3,),
#     dtype=tf.dtypes.float32,
#     name=None
# )
# print(eye_tensor)
# Cách trên chính là cách tạo ra 1 mảng 3 chiều

# Nếu muốn mảng 4 chiều thì chỉ việc thay đổi batch_shape thành 2 chiều = (2,3)

# eye_tensor = tf.eye(
#     num_rows = 5,
#     num_columns=3,
#     batch_shape=(3,2),
#     dtype=tf.dtypes.float32,
#     name=None
# )
# print(eye_tensor)


# Hàm tf.fill() trong TensorFlow được sử dụng để tạo một tensor có các phần tử được điền với giá trị mặc định.
# dims: Đây là một tuple hoặc list chứa các số nguyên, xác định hình dạng (shape) của tensor cần tạo. Ví dụ, nếu bạn muốn tạo một tensor 2 chiều có kích thước 3x4, bạn có thể truyền (3, 4) cho dims.

# value: Giá trị scalar được sử dụng để điền vào các phần tử của tensor mới được tạo.

# name: Tên tùy chọn của hoạt động.

fill_tensor = tf.fill(
    dims = (1,3,4),
    value = 5,
    name=None,
)
print(fill_tensor)


# tf.ones() được sử dụng để tạo một tensor có các phần tử đều có giá trị là 1
#  và có hình dạng được chỉ định bởi shape.
ones_tensor = tf.ones(
    shape = (3,4),
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

# tf.ones_like() được sử dụng để tạo một tensor có cùng hình dạng và kiểu dữ liệu với một tensor khác,
# nhưng tất cả các phần tử trong tensor mới đều có giá trị là 1.
# tf.ones_like(
#     input_tensor,
#     dtype=None,
#     name=None,
#     optimize=True
# )



# Tạo một tensor mẫu
input_tensor = tf.constant([[2, 3], [4, 5]])

# Tạo một tensor mới có cùng hình dạng và kiểu dữ liệu với input_tensor, với tất cả các phần tử là 1
ones_like_tensor = tf.ones_like(input_tensor)

# In tensor mới ra màn hình
print(ones_like_tensor)

# Kết quả:
# [[1 1]
#  [1 1]]

# tf.zeros() được sử dụng để tạo một tensor có các phần tử đều có giá trị là 0 và có hình dạng được chỉ định bởi shape.

# Tạo một tensor 2 chiều có kích thước 3x4 với tất cả các phần tử có giá trị là 0
zeros_tensor = tf.zeros(shape=(3, 4))

# In tensor ra màn hình
print(zeros_tensor)
print(tf.shape(zeros_tensor))


# Kết quả:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

# rank: số chiều của một tensor
# Scalar (rank 0): Là một giá trị đơn vị, không có chiều.

# Vector(Array) (rank 1): Là một mảng các giá trị, có một chiều.

# Matrix (rank 2): Là một mảng hai chiều các giá trị.

# Tensor (rank n): Là một mảng n chiều các giá trị.

# Trong NumPy, bạn có thể sử dụng ndim để lấy số chiều của một mảng NumPy.

# Trong TensorFlow, bạn có thể sử dụng tf.rank() để lấy số chiều của một tensor TensorFlow.

# Vector (rank 1)
vector = np.array([1, 2, 3])
print(f"Rank của vector: {vector.ndim}")  # Output: 1

# Matrix (rank 2)
matrix = np.array([[1, 2], [3, 4]])
print(f"Rank của matrix: {matrix.ndim}")  # Output: 2

# Tensor (rank 3)
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Rank của tensor: {tensor.ndim}")  # Output: 3

rank_tensor = tf.constant([1, 2, 3])
print(f"Rank của tensor: {tf.rank(rank_tensor)}")  # Output: 1
tf.size(rank_tensor)


In [61]:
# tf.random.normal() trong TensorFlow được sử dụng để tạo một tensor có hình dạng được chỉ định,
# trong đó các giá trị được lấy ngẫu nhiên từ phân phối chuẩn (Gaussian distribution) với các tham số như mean (giá trị trung bình) và stddev (độ lệch chuẩn).
# mean: Mean (giá trị trung bình) của phân phối chuẩn từ đó các giá trị được lấy. Mặc định là 0.0.

# stddev: Độ lệch chuẩn (standard deviation) của phân phối chuẩn. Mặc định là 1.0.
# random_tensor = tf.random.normal(
#     (2,3),
#     mean=100.0,
#     stddev=1.0,
#     dtype=tf.dtypes.float32,
#     seed=None,
#     name=None
# )
# print(random_tensor)

random_tensor = tf.random.uniform(
    shape = (2,4),
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)


# seed=None: Tạo chuỗi số ngẫu nhiên khác nhau mỗi lần chạy chương trình.
# seed=<giá trị>: Tạo chuỗi số ngẫu nhiên giống nhau mỗi lần chạy chương trình,
#  nếu sử dụng cùng một giá trị seed.


# Không cung cấp giá trị seed (seed=None)
tensor1 = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0, seed=None)
print("Tensor 1 (không có seed):\n", tensor1)

# Để các giá trị ngẫu nhiên được tạo ra giống nhau,
# bạn cần đảm bảo rằng cả seed toàn cục và seed cụ thể đều giống nhau cho mỗi lần tạo giá trị ngẫu nhiên.
# Đặt lại seed toàn cục
tf.random.set_seed(5)
# Tạo giá trị ngẫu nhiên với seed cụ thể
val1 = tf.random.uniform(shape=(2,2), maxval=3, dtype=tf.int32, seed=10)
print(val1)

# Đặt lại seed toàn cục
tf.random.set_seed(5)

# Tạo giá trị ngẫu nhiên với seed cụ thể
val3 = tf.random.uniform(shape=(2,2), maxval=3, dtype=tf.int32, seed=10)
print(val3)

# Đặt lại seed toàn cục
tf.random.set_seed(5)
val4 = tf.random.uniform(shape=(2,2), maxval=3, dtype=tf.int32, seed=10)
print(val4)



tf.Tensor(
[[0.6263931  0.5298432  0.7584572  0.5084884 ]
 [0.34415376 0.31959772 0.69165003 0.2665254 ]], shape=(2, 4), dtype=float32)
Tensor 1 (không có seed):
 tf.Tensor(
[[ 0.22652864  0.8106553   0.7466094 ]
 [ 0.7749703   0.72448725  1.4217405 ]
 [-0.08917825  1.3464464  -1.0210733 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2 0]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 0]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 0]
 [1 2]], shape=(2, 2), dtype=int32)
